package com.zerobase.homemate.entity.enums;

public enum UserActionType {
    COMPLETE_CHORE,
    COMPLETE_ANY_CHORE,
    COMPLETE_CHORE_WITH_SPACE,
    COMPLETE_CHORE_RECOMMENDED,
    CREATE_CHORE_WITH_SPACE,
    CREATE_CHORE_MANUAL,
    CREATE_CHORE_RECOMMENDED,
    MISSION_COMPLETED
}
