spring.application.name=homemate

http.client.connect-timeout-ms=3000
http.client.read-timeout-ms=5000

# Secret Key Manage
spring.profiles.active=secret

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Quartz
spring.quartz.job-store-type=jdbc
spring.quartz.jdbc.initialize-schema=always
spring.quartz.properties.org.quartz.scheduler.instanceName=ChoreScheduler
spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
spring.quartz.properties.org.quartz.jobStore.isClustered=false
spring.quartz.properties.org.quartz.jobStore.tablePrefix=QRTZ_
spring.quartz.properties.org.quartz.threadPool.threadCount=10