spring.application.name=homemate

http.client.connect-timeout-ms=3000
http.client.read-timeout-ms=5000

# Secret Key Manage
spring.profiles.active=secret

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379